"""Prompt engineering assets (templates, and later prompt builders)."""

from app.ai.prompts.templates import (
    REQUIREMENT_EXTRACTION_PROMPT,
    REQUIREMENT_EXTRACTION_SYSTEM_PROMPT,
    STANDARD_RECOMMENDATION_PROMPT,
    STANDARD_RECOMMENDATION_SYSTEM_PROMPT,
)

__all__ = [
    "REQUIREMENT_EXTRACTION_PROMPT",
    "REQUIREMENT_EXTRACTION_SYSTEM_PROMPT",
    "STANDARD_RECOMMENDATION_PROMPT",
    "STANDARD_RECOMMENDATION_SYSTEM_PROMPT",
]
